member_list:
  - dxl_name: front_left_link1
    port_name: "/dev/ttyUSB0"
    dxl_id: 14
    baud_rate: 57600
    model_number: 1170
    mode: "position"
    p_gain: 800
    initial_pos: 0.116412463
  - dxl_name: front_left_link2
    port_name: "/dev/ttyUSB0"
    dxl_id: 20
    baud_rate: 57600
    model_number: 1120
    mode: "position"
    p_gain: 400
    initial_pos: 0.311398327
  - dxl_name: front_left_link3
    port_name: "/dev/ttyUSB0"
    dxl_id: 4
    baud_rate: 57600
    model_number: 1120
    mode: "position"
    p_gain: 400
    initial_pos: 0.263845
  - dxl_name: front_right_link1
    port_name: "/dev/ttyUSB0"
    dxl_id: 16
    baud_rate: 57600
    model_number: 1170
    mode: "position"
    p_gain: 800
    initial_pos: 0.061529537
  - dxl_name: front_right_link2
    port_name: "/dev/ttyUSB0"
    dxl_id: 5
    baud_rate: 57600
    model_number: 1120
    mode: "position"
    p_gain: 400
    initial_pos: 0.062893673
  - dxl_name: front_right_link3
    port_name: "/dev/ttyUSB0"
    dxl_id: 10
    baud_rate: 57600
    model_number: 1120
    mode: "position"
    p_gain: 400
    initial_pos: -0.254641
  - dxl_name: back_left_link1
    port_name: "/dev/ttyUSB0"
    dxl_id: 13
    baud_rate: 57600
    model_number: 1170
    mode: "position"
    p_gain: 800
    initial_pos: -0.302023463
  - dxl_name: back_left_link2
    port_name: "/dev/ttyUSB0"
    dxl_id: 1
    baud_rate: 57600
    model_number: 1120
    mode: "position"
    p_gain: 400
    initial_pos: -0.737844327
  - dxl_name: back_left_link3
    port_name: "/dev/ttyUSB0"
    dxl_id: 9
    baud_rate: 57600
    model_number: 1120
    mode: "position"
    p_gain: 400
    initial_pos: -0.481670
  - dxl_name: back_right_link1
    port_name: "/dev/ttyUSB0"
    dxl_id: 15
    baud_rate: 57600
    model_number: 1170
    mode: "position"
    p_gain: 800
    initial_pos: 0.495305463
  - dxl_name: back_right_link2
    port_name: "/dev/ttyUSB0"
    dxl_id: 2
    baud_rate: 57600
    model_number: 1120
    mode: "position"
    p_gain: 400
    initial_pos: 0.302194327
  - dxl_name: back_right_link3
    port_name: "/dev/ttyUSB0"
    dxl_id: 11
    baud_rate: 57600
    model_number: 1120
    mode: "position"
    p_gain: 400
    initial_pos: 0.457126
  - dxl_name: crwlr_fl
    port_name: "/dev/ttyUSB0"
    dxl_id: 23
    baud_rate: 57600
    model_number: 1180
    mode: "velocity"
    p_gain: 400
    initial_pos: 0
  - dxl_name: crwlr_fr
    port_name: "/dev/ttyUSB0"
    dxl_id: 21
    baud_rate: 57600
    model_number: 1180
    mode: "velocity"
    p_gain: 400
    initial_pos: 0
  - dxl_name: crwlr_bl
    port_name: "/dev/ttyUSB0"
    dxl_id: 22
    baud_rate: 57600
    model_number: 1180
    mode: "velocity"
    p_gain: 400
    initial_pos: 0
  - dxl_name: crwlr_br
    port_name: "/dev/ttyUSB0"
    dxl_id: 24
    baud_rate: 57600
    model_number: 1180
    mode: "velocity"
    p_gain: 400
    initial_pos: 0


